name: cicd pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: integration

    steps:
      - uses: actions/checkout@v4
      - name: Use bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29
      - name: Run tests
        run: bun test

  # Deployment protection rules require specific conditions to pass before a job referencing the environment can proceed.
  deploy-prd:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Use bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29
      - name: Run tests
        run: bun test
